[ FEAT ] Cria sink para GCS
arquivei/goduck pull request #49
Opened 2022-10-25 15:10 UTC by rilder-almeida

[ FEAT ] Cria sink para GCS

Problema:

Precisamos criar um worker que vai replicar o XML do CDC do Replicator para o GCS. Não tínhamos até então um sink no goduck para tal operação.

Solução:

Criar um sink para GCS. Para melhor perfomace as escritas serão feitas em paralelo, sem garantia de ordem. Para melhor consistência foi adicionado a opção de configurar o ritrier nativo da sdk do storage do GCS.

Links:

https://www.notion.so/arquiveiofficial/Criar-cdc2storage-para-CTe-ed69e4f8ebab41f284047bd55c71db9d

https://app.clickup.com/t/12912817/DFEVIEW-1520

2022-10-26 14:36 UTC, victormn requested changes

2022-10-26 14:36 UTC, victormn commented on pipeline/gcssink/adapter_gcsclient.go
> +	if message.Data == nil {
essa validação deveria estar dentro do sink, pois é uma regra de negócio

2022-10-26 14:36 UTC, victormn commented on pipeline/gcssink/adapter_gcsclient.go
> +		return errors.E(op, ErrFailedToWriteAtBucket, errors.KV("bucket", message.Bucket), errors.KV("path", message.StoragePath), errors.KV("error", err))
`ErrFailedToWriteAtBucket` deveria ser um error code. Não devemos passar um erro como KV. Mesma consideração para o de baixo

2022-10-26 14:36 UTC, victormn commented on pipeline/gcssink/sink.go
> +	retrierConfig []storage.RetryOption,
Mesma consideração de OptionPattern que falei acima

2022-10-26 14:36 UTC, victormn commented on pipeline/gcssink/sink.go
> +	closeFn := func() error {
o método `clientGateway.Close()` já possui a assinatura `func() error`, não precisando encapsular. Além disso, poderia retornar direto o `clientGateway.Close()` ao invés de passar para a variável `closeFn`

2022-10-26 14:36 UTC, victormn commented on pipeline/gcssink/sink.go
> +	for _, msg := range messages {
aqui eu não tenho certeza, mas talvez precisaria de um `msg := msg`

2022-10-26 14:36 UTC, victormn commented on pipeline/gcssink/sink.go
> +	errs := make(chan error, len(messages))
nit: poderia ter usado o https://pkg.go.dev/golang.org/x/sync/errgroup, ele faz o canal por baixo e deixa mais fácil de ler

2022-10-26 14:36 UTC, victormn commented on pipeline/gcssink/sink.go
> +				errs <- errors.E(ErrInvalidSinkMessage, errors.KV("type", fmt.Sprintf("%T", msg)))
não entendi a necessidade e usabilidade dessa KV "type"

2022-10-26 14:36 UTC, victormn commented on pipeline/gcssink/sink.go
> +	for range messages {
Se for usar o errgroup, como comentado acima (recomendo que use), não precisaria considerar este comentário. 

Porém, essa abordagem é estranha. Imagino que foi feita para garantir que consumiu todos os erros. 

O correto seria primeiro criar novas rotinas para o produtor do canal de erros, ou seja, o range em cima do messages. O código criaria as rotinas e depois seguiria para o próximo trecho de código.

Esse próximo trecho deveria ser uma nova rotina que servirá para fechar o canal de erros logo após o `wg.Wait()`. É uma rotina usada exclusivamente para comunicar "olha, o wg.Wait acabou, terminou de processar todas as mensagens, pode fechar o canal de erros"

Por fim, precisaria ter um trecho que fica lendo do canal de erros, que deveria ser um range em cima do canal ao invés da forma que foi feita. Essa seria a rotina principal do método e ficará travada enquanto o canal de erros não for fechado, responsabilidade da rotina de comunicação, sendo que esta só irá fechar o cana de erros quando os produtores acabarem de consumir message, responsabilidade da rotina do produtor.

Então, em resumo, ficaria algo do tipo

```go
func Store() {
    errs := new(canal de erros)
    for _, msg := range messages {
        wg.Add(1)
        go func() {
            defer wg.Done()
            errs <- err
        }()
    }
    go func() {
        wg.Wait() // ficará travado aqui até acabar de processar tudo
        close(errs)
    }

    for err := range errs {
        // lidar com os erros
    }
}
```

Para entender um pouco mais: https://medium.com/engenharia-arquivei/consumindo-uma-lista-de-forma-eficiente-utilizando-go-d6ceb4efc63

Porém, o errgroup faz tudo isso por baixo, facilitando a nossa vida. Temos exemplos do uso dele em outros projetos

2022-10-26 14:36 UTC, victormn commented on pipeline/gcssink/sink.go
> +		return errors.E(op, ErrFailedToStoreMessages, errors.KV("errors", sliceErrs))
Mesma consideração que feita acima, o `ErrFailedToStoreMessages` deveria ser um error code e o errors não deveria ser um KV. Talvez fazer um método que concatena as mensagens.

2022-11-03 14:39 UTC, marcosbmf requested changes

2022-11-03 14:39 UTC, marcosbmf commented on pipeline/gcssink/sink.go
> +	for range messages {
O que ocorre se o código dentro da goroutine que faz o sink der panic? Caso não coloque nenhuma mensagem no errChan, teríamos um deadlock. Seria interessante colocar recuperação de panic nas goroutines.

2022-11-08 11:43 UTC, marcosbmf approved these changes

2022-11-08 14:36 UTC, merged